import {pathToFileURL} from 'url';
import path from 'path';
const APP=pathToFileURL(path.resolve(import.meta.dirname,'../app/index.html')).href;
import { chromium } from 'playwright';
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1400,height:1000}});
await p.addInitScript(()=>{try{localStorage.setItem('puntea.role','ngo')}catch(e){}});
const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto(APP,{waitUntil:'load'});
await p.waitForTimeout(2000);
await p.evaluate(()=>document.getElementById('map').scrollIntoView({block:'center'}));
await p.waitForTimeout(500);
const before=await p.evaluate(()=>({msg:document.getElementById('mMsg').textContent,first:document.querySelector('.match .school')?.textContent}));
const box=await p.locator('#basehit').boundingBox();
await p.mouse.move(box.x+box.width/2,box.y+box.height/2);
await p.mouse.down();
const t0=Date.now();
for(let i=1;i<=25;i++){await p.mouse.move(box.x+box.width/2-i*12,box.y+box.height/2-i*7);}
const dt=Date.now()-t0;
await p.mouse.up(); await p.waitForTimeout(600);
const after=await p.evaluate(()=>({msg:document.getElementById('mMsg').textContent,first:document.querySelector('.match .school')?.textContent,sel:document.getElementById('mBase').value}));
console.log('before:',JSON.stringify(before));
console.log('after :',JSON.stringify(after));
console.log('25 drag moves in',dt,'ms');
await p.locator('#basehit').focus();
for(let i=0;i<5;i++)await p.keyboard.press('ArrowUp');
await p.waitForTimeout(400);
console.log('after keys:',await p.evaluate(()=>document.getElementById('mMsg').textContent));
console.log('errors:',errs.length?errs:'none');
await b.close();
