import {pathToFileURL} from 'url';
import path from 'path';
const APP=pathToFileURL(path.resolve(import.meta.dirname,'../app/index.html')).href;
import { chromium } from 'playwright';
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1400,height:1000}});
await p.addInitScript(()=>{try{localStorage.setItem('puntea.role','ngo')}catch(e){}});
const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto(APP,{waitUntil:'load'});
await p.waitForTimeout(2200);
await p.evaluate(()=>document.getElementById('map').scrollIntoView({block:'center'}));
await p.waitForTimeout(400);
const box=await p.locator('#map').boundingBox();
const y0=await p.evaluate(()=>window.scrollY);
await p.mouse.move(box.x+box.width/2,box.y+box.height/2);
await p.mouse.wheel(0,400); await p.waitForTimeout(350);
console.log('plain wheel over map -> page scrolled:', (await p.evaluate(()=>window.scrollY))!==y0, '| zoom:', await p.evaluate(()=>document.getElementById('zLvl').textContent));
await p.evaluate(()=>document.getElementById('map').scrollIntoView({block:'center'}));
await p.waitForTimeout(300);
await p.keyboard.down('Control');
await p.mouse.move(box.x+box.width/2,box.y+box.height/2);
await p.mouse.wheel(0,-400); await p.waitForTimeout(300);
await p.keyboard.up('Control');
console.log('ctrl+wheel -> zoom:', await p.evaluate(()=>document.getElementById('zLvl').textContent));
await p.click('#zIn'); await p.click('#zIn'); await p.waitForTimeout(300);
console.log('after 2x + button:', await p.evaluate(()=>document.getElementById('zLvl').textContent));
console.log('errors:',errs.length?errs:'none');
await b.close();
