/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindSchoolRouteImport } from './routes/find-school'
import { Route as NationalRouteImport } from './routes/national'
import { Route as SupportRouteImport } from './routes/support'
import { Route as CountyCountyRouteImport } from './routes/county.$county'
import { Route as NgoNgoIdRouteImport } from './routes/ngo.$ngoId'
import { Route as SchoolSchoolIdIndexRouteImport } from './routes/school.$schoolId.index'
import { Route as SchoolSchoolIdSupportRouteImport } from './routes/school.$schoolId.support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindSchoolRoute = FindSchoolRouteImport.update({
  id: '/find-school',
  path: '/find-school',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalRoute = NationalRouteImport.update({
  id: '/national',
  path: '/national',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const CountyCountyRoute = CountyCountyRouteImport.update({
  id: '/county/$county',
  path: '/county/$county',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoNgoIdRoute = NgoNgoIdRouteImport.update({
  id: '/ngo/$ngoId',
  path: '/ngo/$ngoId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolSchoolIdIndexRoute = SchoolSchoolIdIndexRouteImport.update({
  id: '/school/$schoolId/',
  path: '/school/$schoolId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolSchoolIdSupportRoute = SchoolSchoolIdSupportRouteImport.update({
  id: '/school/$schoolId/support',
  path: '/school/$schoolId/support',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-school': typeof FindSchoolRoute
  '/national': typeof NationalRoute
  '/support': typeof SupportRoute
  '/county/$county': typeof CountyCountyRoute
  '/ngo/$ngoId': typeof NgoNgoIdRoute
  '/school/$schoolId/support': typeof SchoolSchoolIdSupportRoute
  '/school/$schoolId/': typeof SchoolSchoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-school': typeof FindSchoolRoute
  '/national': typeof NationalRoute
  '/support': typeof SupportRoute
  '/county/$county': typeof CountyCountyRoute
  '/ngo/$ngoId': typeof NgoNgoIdRoute
  '/school/$schoolId/support': typeof SchoolSchoolIdSupportRoute
  '/school/$schoolId': typeof SchoolSchoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-school': typeof FindSchoolRoute
  '/national': typeof NationalRoute
  '/support': typeof SupportRoute
  '/county/$county': typeof CountyCountyRoute
  '/ngo/$ngoId': typeof NgoNgoIdRoute
  '/school/$schoolId/support': typeof SchoolSchoolIdSupportRoute
  '/school/$schoolId/': typeof SchoolSchoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-school'
    | '/national'
    | '/support'
    | '/county/$county'
    | '/ngo/$ngoId'
    | '/school/$schoolId/support'
    | '/school/$schoolId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-school'
    | '/national'
    | '/support'
    | '/county/$county'
    | '/ngo/$ngoId'
    | '/school/$schoolId/support'
    | '/school/$schoolId'
  id:
    | '__root__'
    | '/'
    | '/find-school'
    | '/national'
    | '/support'
    | '/county/$county'
    | '/ngo/$ngoId'
    | '/school/$schoolId/support'
    | '/school/$schoolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindSchoolRoute: typeof FindSchoolRoute
  NationalRoute: typeof NationalRoute
  SupportRoute: typeof SupportRoute
  CountyCountyRoute: typeof CountyCountyRoute
  NgoNgoIdRoute: typeof NgoNgoIdRoute
  SchoolSchoolIdSupportRoute: typeof SchoolSchoolIdSupportRoute
  SchoolSchoolIdIndexRoute: typeof SchoolSchoolIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-school': {
      id: '/find-school'
      path: '/find-school'
      fullPath: '/find-school'
      preLoaderRoute: typeof FindSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national': {
      id: '/national'
      path: '/national'
      fullPath: '/national'
      preLoaderRoute: typeof NationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/county/$county': {
      id: '/county/$county'
      path: '/county/$county'
      fullPath: '/county/$county'
      preLoaderRoute: typeof CountyCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/$ngoId': {
      id: '/ngo/$ngoId'
      path: '/ngo/$ngoId'
      fullPath: '/ngo/$ngoId'
      preLoaderRoute: typeof NgoNgoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/$schoolId/': {
      id: '/school/$schoolId/'
      path: '/school/$schoolId'
      fullPath: '/school/$schoolId/'
      preLoaderRoute: typeof SchoolSchoolIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/$schoolId/support': {
      id: '/school/$schoolId/support'
      path: '/school/$schoolId/support'
      fullPath: '/school/$schoolId/support'
      preLoaderRoute: typeof SchoolSchoolIdSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindSchoolRoute: FindSchoolRoute,
  NationalRoute: NationalRoute,
  SupportRoute: SupportRoute,
  CountyCountyRoute: CountyCountyRoute,
  NgoNgoIdRoute: NgoNgoIdRoute,
  SchoolSchoolIdSupportRoute: SchoolSchoolIdSupportRoute,
  SchoolSchoolIdIndexRoute: SchoolSchoolIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
